# https://medium.com/flutter/test-flutter-apps-on-travis-3fd5142ecd8c

language: dart

dart:
  - stable
  - dev

os: linux

dist: trusty

sudo: false

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
    update: true

before_install:
  - echo 'Do nothing'

install:
  - echo 'Do nothing'

before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor

script:
  - ./flutter/bin/flutter test
