// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

User _$UserFromJson(Map<String, dynamic> json) {
  return User(
      json['academic_register'] as String,
      json['address'] as String,
      json['address_number'] as String,
      json['agente'] as String,
      json['birth_city'] as String,
      json['birth_country'] as String,
      json['birth_date'] as String,
      json['birth_state'] as String,
      json['birth_category'] as String,
      json['cep'] as String,
      json['city'] as String,
      json['complement'] as String,
      json['complete_name'] as String,
      json['course'] as String,
      json['cpf'] as String,
      json['date'] as String,
      json['degree'] as int,
      json['document_agent'] as String,
      json['document_state'] as String,
      json['election_title_number'] as String,
      json['election_title_zone'] as String,
      json['email'] as String,
      json['father_name'] as String,
      json['first_name'] as String,
      json['genre'] as String,
      json['institution'] as String,
      json['institution_country'] as String,
      json['institution_state'] as String,
      json['institution_city'] as String,
      json['lattes'] as String,
      json['mother_name'] as String,
      json['nacionality'] as String,
      json['neighborhood'] as String,
      json['number'] as String,
      json['rg'] as String,
      json['social_name'] as String,
      json['state'] as String,
      json['telephone'] as String,
      json['type'] as String,
      json['year'] as int);
}

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'academic_register': instance.academicRegister,
      'address': instance.address,
      'address_number': instance.addressNumber,
      'agente': instance.agente,
      'birth_city': instance.birthCity,
      'birth_country': instance.birthCountry,
      'birth_date': instance.birthDate,
      'birth_state': instance.birthState,
      'birth_category': instance.birthCategory,
      'cep': instance.cep,
      'city': instance.city,
      'complement': instance.complement,
      'complete_name': instance.completeName,
      'course': instance.course,
      'cpf': instance.cpf,
      'date': instance.date,
      'degree': instance.degree,
      'document_agent': instance.documentAgent,
      'document_state': instance.documentState,
      'election_title_number': instance.electionTitleNumber,
      'election_title_zone': instance.electionTitleZone,
      'email': instance.email,
      'father_name': instance.fatherName,
      'first_name': instance.firstName,
      'genre': instance.genre,
      'institution': instance.institution,
      'institution_country': instance.institutionCountry,
      'institution_state': instance.institutionState,
      'institution_city': instance.institutionCity,
      'lattes': instance.lattes,
      'mother_name': instance.motherName,
      'nacionality': instance.nacionality,
      'neighborhood': instance.neighborhood,
      'number': instance.number,
      'rg': instance.rg,
      'social_name': instance.socialName,
      'state': instance.state,
      'telephone': instance.telephone,
      'type': instance.type,
      'year': instance.year
    };
